### ISSUE TITLE
(void-function with-peg-rules)

### ISSUE THREAD

**Issue by novoid** [toshism/org-linker#5]
Hi,

After having upgraded my packages, I do think, I've found an issue with org-linker b031116:

```
Error running timer: 
(error "In ‘org-linker target’ source: ‘(closure ((name . org-linker target) 
    (--cl-rest-- :name org-linker target) 
    (buffers-files $MY-CURRENT-BUFFER $MY-ORG-AGENDA-FILES-LIST) t) nil 
       (let* ((query (org-ql--query-string-to-sexp helm-pattern)) 
          (window-width (window-width (helm-window)))) 
          (if query 
             (progn (save-current-buffer (set-buffer (helm-buffer-get)) 
                    (setq helm-org-ql-buffers-files buffers-files)) 
               (condition-case nil (progn (org-ql-select buffers-files query :action 
               (list (quote helm-org-ql--heading) window-width))) (error nil))))))’ 

 (void-function with-peg-rules)")
```

I guess this is related to helm. Should I provide more information? Which?

**Comment by yantar92** [comment]
This is related to `org-ql`. `org-ql` is using `peg` package to parse search string. Probably your version of `peg` is outdated.

**Comment by toshism** [comment]
Thanks @novoid and @yantar92 . Let me know if upgrading `peg` doesn't fix this and I'll look into it.

**Comment by novoid** [comment]
> Probably your version of `peg` is outdated.

My version is installed via use-package/elpa and it is from 2015-07 - how can this be out of date? 😜

OK, ok, I need to find a way of getting an up to date version from a different installation path.

**Comment by novoid** [comment]
Yes, I can confirm that switching from the 2015-07 version to a manually downloaded up-to-date version fixed the issue. Thanks for helping me @toshism !

**Comment by toshism** [comment]
Sweet, glad that was an easy fix. 👍
